import type { CMSSnapshot } from './types';

// Mock content used until Supabase is connected. Admins can edit all of it from /admin,
// and "Reset demo data" in Settings restores this file.

const px = (id: number, w = 1600) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

export const IMAGES = {
  everest: px(691668),
  annapurna: px(1271619),
  alps: px(1624496),
  patagonia: px(1566837),
  kilimanjaro: px(1365425),
  andes: px(1252814),
  dolomites: px(1440476),
  ridge: px(1647962),
  towers: px(1559821),
  tentSunset: px(2398220),
  forestTrail: px(1578750),
  lake: px(417074),
  snowMoon: px(1287145),
  lonePeak: px(1054218),
};

const portrait = (id: number) => px(id, 400);

const T = '2026-01-01T00:00:00.000Z';
const meta = (id: string, createdAt = T) => ({ id, createdAt, updatedAt: createdAt });

export const seed: CMSSnapshot = {
  treks: [
    {
      ...meta('trk-kedarkantha'),
      slug: 'kedarkantha-trek',
      name: 'Kedarkantha Winter Trek',
      region: 'Uttarakhand',
      country: 'India',
      durationDays: 6,
      price: 9999,
      originalPrice: 11999,
      difficulty: 'Moderate',
      maxAltitude: '3,810 m',
      bestTime: 'Dec – Apr',
      groupSize: '8 – 16 trekkers',
      summary: 'The classic Himalayan winter summit. Snow-laden pine forests, frozen Juda ka Talab and a 360° sunrise over Swargarohini.',
      description:
        "Kedarkantha is India's favourite winter trek for a reason. Starting from the village of Sankri, the trail winds through dense oak and pine forests, opens onto snow meadows and campsites with uninterrupted views, and ends with a dawn summit push that reveals more than a dozen Garhwal peaks at once. It's the perfect first Himalayan summit.",
      image: IMAGES.lonePeak,
      gallery: [IMAGES.lonePeak, IMAGES.tentSunset, IMAGES.forestTrail, IMAGES.snowMoon],
      highlights: [
        'Summit at 3,810 m with views of Swargarohini, Bandarpoonch and Kalanag',
        'Camp beside the frozen Juda ka Talab lake',
        'Walk through snow-covered pine and oak forests',
        'Experience village life in Sankri, Govind Pashu Vihar',
      ],
      itinerary: [
        { title: 'Dehradun to Sankri', description: 'Scenic 8-hour drive along the Yamuna and Tons rivers to the base village of Sankri.', distance: '200 km drive', altitude: '1,920 m' },
        { title: 'Sankri to Juda ka Talab', description: 'Climb through pine forests to a high-altitude lake camp.', distance: '4 km', altitude: '2,780 m' },
        { title: 'Juda ka Talab to Base Camp', description: 'Short day into wide snow meadows with the summit in sight.', distance: '4 km', altitude: '3,430 m' },
        { title: 'Summit day', description: 'Pre-dawn start, summit at sunrise, then descend to Hargaon camp.', distance: '9 km', altitude: '3,810 m' },
        { title: 'Hargaon to Sankri', description: 'Gentle descent through forests back to Sankri.', distance: '6 km', altitude: '1,920 m' },
        { title: 'Sankri to Dehradun', description: 'Drive back to Dehradun, arriving by evening.', distance: '200 km drive' },
      ],
      inclusions: ['Certified trek leader & local guides', 'All meals from Day 1 dinner to Day 6 breakfast', 'Tents, sleeping bags & mattresses', 'Forest permits and camping fees', 'Dehradun – Sankri – Dehradun transport', 'First-aid kit, oximeter & oxygen cylinder'],
      exclusions: ['Personal expenses and tips', 'Travel insurance', 'Porter for personal backpack', 'Anything not listed in inclusions'],
      departures: ['2026-12-12', '2026-12-19', '2026-12-26', '2027-01-09', '2027-01-23'],
      rating: 4.9,
      reviewCount: 1284,
      featured: true,
      status: 'published',
    },
    {
      ...meta('trk-hampta'),
      slug: 'hampta-pass-trek',
      name: 'Hampta Pass Crossover',
      region: 'Himachal Pradesh',
      country: 'India',
      durationDays: 5,
      price: 10499,
      difficulty: 'Moderate',
      maxAltitude: '4,270 m',
      bestTime: 'Jun – Sep',
      groupSize: '8 – 15 trekkers',
      summary: "Cross from the green valleys of Kullu into the stark desert of Lahaul, then finish beside Chandratal's turquoise waters.",
      description:
        'Few treks offer a landscape change as dramatic as Hampta Pass. You begin in lush, flower-filled valleys above Manali and, after crossing the pass, descend into the barren, high-altitude desert of Spiti and Lahaul. A visit to Chandratal lake caps one of the best monsoon treks in India.',
      image: IMAGES.annapurna,
      gallery: [IMAGES.annapurna, IMAGES.lake, IMAGES.tentSunset, IMAGES.ridge],
      highlights: ['Dramatic shift from Kullu greenery to Lahaul desert', 'Cross the 4,270 m Hampta Pass', 'Visit Chandratal, the moon lake', 'River crossings and wildflower meadows'],
      itinerary: [
        { title: 'Manali to Jobra, trek to Chika', description: 'Drive to Jobra and walk an easy trail to the riverside Chika campsite.', distance: '2 km', altitude: '3,100 m' },
        { title: 'Chika to Balu ka Ghera', description: 'Follow the Rani Nallah through meadows to a sandy campsite.', distance: '9 km', altitude: '3,660 m' },
        { title: 'Cross Hampta Pass to Shea Goru', description: 'Steep climb to the pass and a long descent into Lahaul.', distance: '12 km', altitude: '4,270 m' },
        { title: 'Shea Goru to Chatru, Chandratal visit', description: 'Short walk to Chatru then drive to Chandratal lake.', distance: '7 km' },
        { title: 'Chatru to Manali', description: 'Drive back via Rohtang/Atal Tunnel.', distance: '75 km drive' },
      ],
      inclusions: ['Experienced trek leader', 'All meals during the trek', 'Camping equipment', 'Permits and Chandratal visit', 'Manali pickup and drop'],
      exclusions: ['Travel to Manali', 'Insurance', 'Personal gear', 'Tips'],
      departures: ['2027-06-13', '2027-06-27', '2027-07-11', '2027-08-01', '2027-08-22'],
      rating: 4.8,
      reviewCount: 936,
      featured: true,
      status: 'published',
    },
    {
      ...meta('trk-vof'),
      slug: 'valley-of-flowers-trek',
      name: 'Valley of Flowers & Hemkund',
      region: 'Uttarakhand',
      country: 'India',
      durationDays: 6,
      price: 12999,
      difficulty: 'Easy',
      maxAltitude: '4,329 m',
      bestTime: 'Jul – Sep',
      groupSize: '10 – 18 trekkers',
      summary: 'A UNESCO World Heritage valley carpeted with 500+ species of alpine flowers, paired with the glacial lake at Hemkund Sahib.',
      description:
        'In monsoon the Bhyundar valley turns into a living painting. Waterfalls, glaciers and endless meadows of blue poppies, cobra lilies and primulas make this one of the most photogenic walks in the Himalaya. The pilgrimage climb to Hemkund Sahib adds a high-altitude challenge.',
      image: IMAGES.forestTrail,
      gallery: [IMAGES.forestTrail, IMAGES.lake, IMAGES.snowMoon],
      highlights: ['Walk through a UNESCO World Heritage Site', '500+ species of alpine flora in bloom', 'Hemkund Sahib glacial lake at 4,329 m', 'Stay in Ghangaria village'],
      itinerary: [
        { title: 'Rishikesh to Joshimath', description: 'Long scenic drive along the Alaknanda.', distance: '270 km drive', altitude: '1,890 m' },
        { title: 'Govindghat to Ghangaria', description: 'Steady climb along the Pushpawati river.', distance: '10 km', altitude: '3,050 m' },
        { title: 'Valley of Flowers', description: 'Full day exploring the valley meadows.', distance: '8 km', altitude: '3,658 m' },
        { title: 'Hemkund Sahib', description: 'Steep climb to the sacred glacial lake.', distance: '12 km', altitude: '4,329 m' },
        { title: 'Ghangaria to Joshimath', description: 'Descend and drive to Joshimath.', distance: '10 km' },
        { title: 'Joshimath to Rishikesh', description: 'Drive back to Rishikesh.', distance: '270 km drive' },
      ],
      inclusions: ['Trek leader and guide', 'Guesthouse stays', 'All meals', 'Park entry fees', 'Rishikesh transport'],
      exclusions: ['Mule or porter charges', 'Insurance', 'Personal expenses'],
      departures: ['2027-07-17', '2027-07-31', '2027-08-14', '2027-08-28'],
      rating: 4.8,
      reviewCount: 712,
      featured: true,
      status: 'published',
    },
    {
      ...meta('trk-kgl'),
      slug: 'kashmir-great-lakes-trek',
      name: 'Kashmir Great Lakes',
      region: 'Jammu & Kashmir',
      country: 'India',
      durationDays: 8,
      price: 19999,
      originalPrice: 22999,
      difficulty: 'Challenging',
      maxAltitude: '4,200 m',
      bestTime: 'Jul – Sep',
      groupSize: '8 – 14 trekkers',
      summary: 'Seven alpine lakes, three high passes and endless meadows. Often called the most beautiful trek in India.',
      description:
        "Each day of the Kashmir Great Lakes trek brings a new lake: Vishansar, Kishansar, Gadsar, Satsar and the twin lakes of Gangabal and Nundkol beneath Mt Harmukh. Between them lie wide meadows grazed by shepherds' flocks and three passes with wide valley views.",
      image: IMAGES.lake,
      gallery: [IMAGES.lake, IMAGES.alps, IMAGES.dolomites, IMAGES.tentSunset],
      highlights: ['Seven turquoise alpine lakes', 'Cross Nichnai, Gadsar & Zaj passes', 'Camp below Mt Harmukh', "Meet Bakarwal shepherds"],
      itinerary: [
        { title: 'Srinagar to Sonamarg', description: 'Drive to base camp in Shitkadi.', altitude: '2,730 m' },
        { title: 'Sonamarg to Nichnai', description: 'Climb through maple and birch forests.', distance: '11 km', altitude: '3,500 m' },
        { title: 'Nichnai to Vishansar', description: 'Cross Nichnai pass to the first great lake.', distance: '12 km', altitude: '3,650 m' },
        { title: 'Vishansar to Gadsar', description: 'Highest pass of the trek with twin lake views.', distance: '14 km', altitude: '4,200 m' },
        { title: 'Gadsar to Satsar', description: 'Meadow walk to the seven lakes of Satsar.', distance: '12 km', altitude: '3,600 m' },
        { title: 'Satsar to Gangabal', description: 'Boulder sections and the stunning twin lakes.', distance: '11 km', altitude: '3,500 m' },
        { title: 'Gangabal to Naranag', description: 'Long descent through pine forests.', distance: '11 km', altitude: '2,270 m' },
        { title: 'Drive to Srinagar', description: 'Return to Srinagar.' },
      ],
      inclusions: ['Trek leader & mountain team', 'All camping meals', 'Tents, sleeping bags', 'Permits', 'Srinagar transfers'],
      exclusions: ['Flights to Srinagar', 'Insurance', 'Personal porter', 'Tips'],
      departures: ['2027-07-04', '2027-07-18', '2027-08-08', '2027-08-29'],
      rating: 4.9,
      reviewCount: 588,
      featured: true,
      status: 'published',
    },
    {
      ...meta('trk-brahmatal'),
      slug: 'brahmatal-trek',
      name: 'Brahmatal Lake Trek',
      region: 'Uttarakhand',
      country: 'India',
      durationDays: 6,
      price: 10999,
      difficulty: 'Moderate',
      maxAltitude: '3,734 m',
      bestTime: 'Dec – Mar',
      groupSize: '8 – 16 trekkers',
      summary: 'A ridge walk with front-row views of Trishul and Nanda Ghunti, ending at a frozen mountain lake.',
      description:
        'Brahmatal gives you big-mountain views from almost every campsite. Ridge walks above the tree line, frozen Bekaltal and Brahmatal lakes and a summit with Trishul and Nanda Ghunti close enough to touch make it a strong alternative to Kedarkantha.',
      image: IMAGES.snowMoon,
      gallery: [IMAGES.snowMoon, IMAGES.lonePeak, IMAGES.ridge],
      highlights: ['Close views of Mt Trishul and Nanda Ghunti', 'Two frozen lakes', 'Ridge walks above the clouds'],
      itinerary: [
        { title: 'Kathgodam to Lohajung', description: 'Drive through Kumaon hills.', altitude: '2,330 m' },
        { title: 'Lohajung to Bekaltal', description: 'Forest trail to the first lake.', distance: '6 km', altitude: '2,960 m' },
        { title: 'Bekaltal to Telandi', description: 'Ridge climb with big views.', distance: '6 km', altitude: '3,400 m' },
        { title: 'Brahmatal summit & lake', description: 'Summit push and descent to Brahmatal.', distance: '8 km', altitude: '3,734 m' },
        { title: 'Back to Lohajung', description: 'Descend through forests.', distance: '9 km' },
        { title: 'Lohajung to Kathgodam', description: 'Drive back.' },
      ],
      inclusions: ['Trek leader', 'All meals', 'Camping gear', 'Permits', 'Transport from Kathgodam'],
      exclusions: ['Insurance', 'Personal expenses', 'Porter'],
      departures: ['2026-12-20', '2027-01-03', '2027-01-17', '2027-02-07'],
      rating: 4.7,
      reviewCount: 403,
      featured: false,
      status: 'published',
    },
    {
      ...meta('trk-goechala'),
      slug: 'goechala-trek',
      name: 'Goechala Kanchenjunga View',
      region: 'Sikkim',
      country: 'India',
      durationDays: 11,
      price: 24999,
      difficulty: 'Expert',
      maxAltitude: '4,600 m',
      bestTime: 'Apr – May, Oct – Nov',
      groupSize: '6 – 12 trekkers',
      summary: "Stand face-to-face with Kanchenjunga, the world's third-highest mountain, at sunrise from Goechala viewpoint.",
      description:
        "Goechala takes you deep into Kanchenjunga National Park through rhododendron forests, yak pastures and glacial moraine to Samiti lake and the viewpoint below the Kanchenjunga massif. It's long and demanding, and well worth the effort.",
      image: IMAGES.everest,
      gallery: [IMAGES.everest, IMAGES.ridge, IMAGES.lake],
      highlights: ['Sunrise on Kanchenjunga (8,586 m)', 'Rhododendron forests in bloom', 'Samiti lake reflections'],
      itinerary: [
        { title: 'NJP to Yuksom', description: 'Drive into West Sikkim.', altitude: '1,780 m' },
        { title: 'Yuksom to Sachen', description: 'Forest trail along the Prek Chu.', distance: '8 km' },
        { title: 'Sachen to Tshoka', description: 'Climb to a Tibetan settlement.', distance: '7 km', altitude: '3,000 m' },
        { title: 'Tshoka to Dzongri', description: 'Rhododendron forests to Dzongri.', distance: '9 km', altitude: '4,020 m' },
        { title: 'Dzongri to Thansing', description: 'Descend to Kockchurang and on to Thansing.', distance: '10 km' },
        { title: 'Goechala viewpoint', description: 'Pre-dawn walk to the viewpoint.', altitude: '4,600 m' },
        { title: 'Return to Yuksom', description: 'Retrace the route over three days.' },
      ],
      inclusions: ['Expert trek leader', 'All meals', 'Camping gear', 'Park permits', 'NJP transfers'],
      exclusions: ['Insurance', 'Personal porter', 'Tips'],
      departures: ['2026-10-10', '2026-10-24', '2027-04-17'],
      rating: 4.9,
      reviewCount: 241,
      featured: false,
      status: 'published',
    },
    {
      ...meta('trk-roopkund'),
      slug: 'roopkund-trek',
      name: 'Roopkund Mystery Lake',
      region: 'Uttarakhand',
      country: 'India',
      durationDays: 8,
      price: 16999,
      difficulty: 'Challenging',
      maxAltitude: '5,029 m',
      bestTime: 'May – Jun, Sep – Oct',
      groupSize: '8 – 14 trekkers',
      summary: "Bedni Bugyal's rolling meadows, Trishul up close and the legendary 'skeleton lake' at over 5,000 m.",
      description:
        "Roopkund combines some of the finest high-altitude meadows in the country with a hard final climb to the famous lake. On the way you'll camp at Ali and Bedni Bugyal, among the largest meadows in Asia.",
      image: IMAGES.ridge,
      gallery: [IMAGES.ridge, IMAGES.alps, IMAGES.tentSunset],
      highlights: ['Ali & Bedni Bugyal meadows', 'Roopkund lake at 5,029 m', 'Views of Trishul & Nanda Ghunti'],
      itinerary: [
        { title: 'Kathgodam to Lohajung', description: 'Drive to base.' },
        { title: 'Lohajung to Didna', description: 'Descend to the Neel Ganga then climb to Didna village.' },
        { title: 'Didna to Ali Bugyal', description: 'Climb to the meadows.' },
        { title: 'Ali Bugyal to Patar Nachauni', description: 'Meadow walk.' },
        { title: 'To Bhagwabasa', description: 'Cross Kalu Vinayak.' },
        { title: 'Roopkund & back', description: 'Summit day.' },
        { title: 'Descend to Lohajung', description: 'Long descent.' },
        { title: 'Drive to Kathgodam', description: 'Return.' },
      ],
      inclusions: ['Trek leader', 'Meals', 'Gear', 'Permits'],
      exclusions: ['Insurance', 'Personal porter'],
      departures: ['2026-10-10', '2027-05-15', '2027-05-29'],
      rating: 4.8,
      reviewCount: 356,
      featured: false,
      status: 'published',
    },
    {
      ...meta('trk-chadar'),
      slug: 'chadar-frozen-river-trek',
      name: 'Chadar Frozen River',
      region: 'Ladakh',
      country: 'India',
      durationDays: 9,
      price: 27999,
      difficulty: 'Expert',
      maxAltitude: '3,390 m',
      bestTime: 'Jan – Feb',
      groupSize: '6 – 12 trekkers',
      summary: 'Walk on the frozen Zanskar river through towering gorges in −25 °C. A winter expedition unlike any other.',
      description:
        'Every winter, the Zanskar river freezes into a sheet of ice, the chadar, that has long been the only winter route for villagers in Zanskar. Walking on it between sheer canyon walls, with frozen waterfalls and nights in caves and tents, is one of the hardest and most memorable treks in India.',
      image: IMAGES.towers,
      gallery: [IMAGES.towers, IMAGES.snowMoon],
      highlights: ['Walk on the frozen Zanskar river', 'Nerak frozen waterfall', 'Ladakhi culture in deep winter'],
      itinerary: [
        { title: 'Arrive in Leh', description: 'Acclimatise in Leh.' },
        { title: 'Acclimatisation & medical check', description: 'Mandatory checks.' },
        { title: 'Drive to Shingra Koma, trek to Tilad Do', description: 'First steps on the ice.' },
        { title: 'Tilad Do to Tibb cave', description: 'Long day on the chadar.' },
        { title: 'Tibb to Nerak', description: 'See the frozen waterfall.' },
        { title: 'Return trek', description: 'Back towards Shingra Koma over two days.' },
        { title: 'Drive to Leh', description: 'Return.' },
      ],
      inclusions: ['Leh stay', 'Trek leader', 'Meals', 'Winter gear', 'Permits & insurance mandated by ALTOA'],
      exclusions: ['Flights', 'Personal gear', 'Tips'],
      departures: ['2027-01-12', '2027-01-26', '2027-02-09'],
      rating: 4.7,
      reviewCount: 189,
      featured: false,
      status: 'published',
    },
    {
      ...meta('trk-ebc'),
      slug: 'everest-base-camp-trek',
      name: 'Everest Base Camp',
      region: 'Khumbu',
      country: 'Nepal',
      durationDays: 14,
      price: 124999,
      originalPrice: 139999,
      difficulty: 'Challenging',
      maxAltitude: '5,364 m',
      bestTime: 'Mar – May, Sep – Nov',
      groupSize: '8 – 12 trekkers',
      summary: "Fly into Lukla, walk through Sherpa villages and stand at the foot of the world's highest mountain.",
      description:
        'The Everest Base Camp trek follows the Khumbu valley past Namche Bazaar, Tengboche monastery and Gorak Shep to base camp, with a sunrise climb to Kala Patthar for the best view of Everest itself.',
      image: IMAGES.alps,
      gallery: [IMAGES.alps, IMAGES.everest, IMAGES.dolomites, IMAGES.kilimanjaro],
      highlights: ['Sunrise from Kala Patthar (5,545 m)', 'Tengboche monastery', 'Namche Bazaar', 'Khumbu glacier'],
      itinerary: [
        { title: 'Arrive Kathmandu', description: 'Welcome briefing.' },
        { title: 'Fly to Lukla, trek to Phakding', description: 'Mountain flight.' },
        { title: 'Phakding to Namche Bazaar', description: 'Cross suspension bridges.' },
        { title: 'Acclimatisation in Namche', description: 'Hike to Everest View Hotel.' },
        { title: 'Namche to Tengboche', description: 'Monastery visit.' },
        { title: 'Tengboche to Dingboche', description: 'Into the high valley.' },
        { title: 'Dingboche to Lobuche', description: 'Memorial site at Thukla.' },
        { title: 'Everest Base Camp', description: 'Reach EBC via Gorak Shep.' },
        { title: 'Kala Patthar & descent', description: 'Sunrise views, descend to Pheriche.' },
        { title: 'Return to Lukla & Kathmandu', description: 'Over three days.' },
      ],
      inclusions: ['Licensed guide & porters', 'Teahouse stays', 'All meals on trek', 'Kathmandu–Lukla flights', 'Permits'],
      exclusions: ['International flights', 'Nepal visa', 'Insurance', 'Tips'],
      departures: ['2026-10-03', '2026-10-17', '2027-04-04'],
      rating: 4.9,
      reviewCount: 422,
      featured: true,
      status: 'published',
    },
  ],

  bookings: [
    { ...meta('bk-1001', '2026-09-28T10:20:00.000Z'), trekId: 'trk-kedarkantha', trekName: 'Kedarkantha Winter Trek', customerName: 'Aarav Mehta', email: 'aarav@example.com', phone: '+91 98100 11223', departureDate: '2026-12-19', participants: 3, amount: 29997, status: 'confirmed' },
    { ...meta('bk-1002', '2026-09-29T08:05:00.000Z'), trekId: 'trk-kgl', trekName: 'Kashmir Great Lakes', customerName: 'Priya Sharma', email: 'priya.s@example.com', phone: '+91 99300 44556', departureDate: '2026-08-09', participants: 2, amount: 39998, status: 'completed' },
    { ...meta('bk-1003', '2026-09-30T14:40:00.000Z'), trekId: 'trk-ebc', trekName: 'Everest Base Camp', customerName: 'Rohan Iyer', email: 'rohan.iyer@example.com', phone: '+91 90040 77889', departureDate: '2026-10-17', participants: 1, amount: 124999, status: 'pending', notes: 'Asked about extra night in Kathmandu.' },
    { ...meta('bk-1004', '2026-09-30T18:12:00.000Z'), trekId: 'trk-hampta', trekName: 'Hampta Pass Crossover', customerName: 'Sneha Kapoor', email: 'sneha.k@example.com', phone: '+91 98765 43210', departureDate: '2026-08-23', participants: 4, amount: 41996, status: 'cancelled' },
    { ...meta('bk-1005', '2026-10-01T06:30:00.000Z'), trekId: 'trk-brahmatal', trekName: 'Brahmatal Lake Trek', customerName: 'Kabir Singh', email: 'kabir@example.com', phone: '+91 91234 56789', departureDate: '2027-01-03', participants: 2, amount: 21998, status: 'pending' },
  ],

  inquiries: [
    { ...meta('inq-1', '2026-09-30T09:10:00.000Z'), name: 'Ananya Rao', email: 'ananya@example.com', phone: '+91 98450 12345', subject: 'Corporate group of 20', message: 'We are planning an offsite trek for 20 colleagues in December. Can you suggest an easy option and share group pricing?', trekInterest: 'Kedarkantha Winter Trek', status: 'new' },
    { ...meta('inq-2', '2026-09-29T16:45:00.000Z'), name: 'Vikram Desai', email: 'vikram.d@example.com', subject: 'First Himalayan trek', message: 'I run 5K three times a week. Is Hampta Pass suitable for a first-timer?', trekInterest: 'Hampta Pass Crossover', status: 'replied' },
    { ...meta('inq-3', '2026-09-27T11:00:00.000Z'), name: 'Meera Nair', email: 'meera.nair@example.com', phone: '+91 97000 99887', subject: 'Solo female trekker', message: 'Do you have women-only batches for Valley of Flowers?', status: 'closed' },
  ],

  testimonials: [
    { ...meta('tst-1'), name: 'Aarav Mehta', location: 'Mumbai', trekName: 'Kedarkantha Winter Trek', rating: 5, quote: 'Our trek leader knew every pine on that trail. Summit sunrise was the single best moment of my year, and the camps were warmer than my flat.', avatar: portrait(1222271), published: true },
    { ...meta('tst-2'), name: 'Priya Sharma', location: 'Bengaluru', trekName: 'Kashmir Great Lakes', rating: 5, quote: 'Seven lakes, zero stress. Everything from permits to food was taken care of, so all I had to do was walk and look up.', avatar: portrait(1130626), published: true },
    { ...meta('tst-3'), name: 'Emily Davis', location: 'London', trekName: 'Everest Base Camp', rating: 5, quote: 'Flawless logistics and a team that genuinely cared about acclimatisation. I never once felt rushed or unsafe.', avatar: portrait(1239291), published: true },
    { ...meta('tst-4'), name: 'Rohan Iyer', location: 'Pune', trekName: 'Hampta Pass Crossover', rating: 5, quote: 'Green valley on day two, moon-desert on day three. The crossover is unreal, and the crew made the river crossings feel easy.', published: true },
  ],

  team: [
    { ...meta('tm-1'), name: 'Tenzing Negi', role: 'Founder & Lead Guide', bio: 'Grew up in Kinnaur and has led 300+ Himalayan treks over 15 years. NIM-certified mountaineer.', photo: portrait(1222271), order: 1 },
    { ...meta('tm-2'), name: 'Ishita Rawat', role: 'Head of Operations', bio: 'Runs logistics, permits and safety systems so every batch leaves on time and comes back smiling.', photo: portrait(1130626), order: 2 },
    { ...meta('tm-3'), name: 'Arjun Thakur', role: 'Senior Trek Leader', bio: 'Wilderness first responder with a habit of finding the best sunrise spot on every trail.', photo: portrait(1239291), order: 3 },
  ],

  faqs: [
    { ...meta('faq-1'), question: 'I have never trekked before. Which trek should I start with?', answer: 'Kedarkantha (winter) or Valley of Flowers (monsoon) are ideal first treks. Both are well-marked, have comfortable campsites and gradual altitude gain.', order: 1, published: true },
    { ...meta('faq-2'), question: 'How fit do I need to be?', answer: 'You should be able to jog 5 km in under 35 minutes before an Easy or Moderate trek. We send a 6-week fitness plan after you book.', order: 2, published: true },
    { ...meta('faq-3'), question: 'What is your cancellation policy?', answer: 'Cancel 30+ days before departure for a full refund minus a 5% processing fee. Between 15–30 days you get 50% back or a full trek voucher.', order: 3, published: true },
    { ...meta('faq-4'), question: 'Is it safe for solo women trekkers?', answer: 'Absolutely. Around 40% of our trekkers are women and many travel solo. We run women-only batches every month and assign same-gender tent mates.', order: 4, published: true },
    { ...meta('faq-5'), question: 'What safety equipment do you carry?', answer: 'Every batch carries oxygen cylinders, pulse oximeters, a full medical kit and satellite communication on remote routes. Trek leaders are certified in wilderness first aid.', order: 5, published: true },
    { ...meta('faq-6'), question: 'Can I rent trekking gear?', answer: 'Yes. Jackets, trekking poles, microspikes and backpacks can be rented at the base camp at nominal rates.', order: 6, published: true },
  ],

  home: {
    hero: {
      eyebrow: 'Himalayan treks · Since 2011',
      title: 'Chal oye,',
      highlight: 'the mountains are calling.',
      subtitle: 'Small groups, certified trek leaders and campsites with a view. Handpicked Himalayan trails for first-timers and summit chasers alike.',
      videoUrl: 'https://videos.pexels.com/video-files/3577871/3577871-hd_1920_1080_25fps.mp4',
      posterImage: IMAGES.lonePeak,
      primaryCta: 'Explore treks',
      secondaryCta: 'Talk to a trek expert',
    },
    regions: ['Uttarakhand', 'Himachal', 'Kashmir', 'Ladakh', 'Sikkim', 'Nepal', 'Spiti', 'Garhwal'],
    stats: [
      { value: '18,000+', label: 'Happy trekkers' },
      { value: '45', label: 'Himalayan trails' },
      { value: '4.9/5', label: 'Average rating' },
      { value: '0', label: 'Compromises on safety' },
    ],
    featuresTitle: 'Built by trekkers, for trekkers',
    featuresSubtitle: 'Fifteen years on these trails taught us that the small things make a trek memorable. Here is what you get on every Chal Oye departure.',
    features: [
      { icon: 'shield', title: 'Safety you can see', description: 'Oxygen, oximeters and satellite comms on every batch. Twice-daily health checks by certified leaders.' },
      { icon: 'users', title: 'Small, curated groups', description: 'Never more than 16 trekkers per batch, with a 1:8 leader ratio so nobody gets left behind.' },
      { icon: 'leaf', title: 'Leave no trace', description: 'Every trekker carries an eco-bag. We bring back more waste than we create.' },
      { icon: 'utensils', title: 'Real mountain food', description: 'Hot, fresh, vegetarian meals cooked by our kitchen team. Yes, even pakodas at 3,500 m.' },
    ],
    featuresImage: IMAGES.tentSunset,
    cta: {
      title: 'Your next summit is one conversation away.',
      subtitle: 'Not sure which trek is right for you? Our trek experts reply on WhatsApp within an hour.',
      image: IMAGES.dolomites,
      buttonLabel: 'Plan my trek',
    },
  },

  about: {
    heroTitle: 'We are Chal Oye.',
    heroSubtitle: 'A team of mountain people helping city people find their way back to the hills.',
    heroImage: IMAGES.ridge,
    storyTitle: 'It started with a single trek and a borrowed tent.',
    storyParagraphs: [
      'In 2011, our founder Tenzing led six friends up Kedarkantha with a borrowed tent and a pressure cooker. By the summit, three of them had already asked about the next trip.',
      "Fifteen years later Chal Oye runs 45 trails across the Indian Himalaya and Nepal, but the idea hasn't changed: small groups, local crews, honest pricing and the kind of care you'd expect from a friend who knows the mountains.",
      'Every trek leader is from the hills, every cook is from a nearby village, and a share of every booking goes back to the communities that host us.',
    ],
    storyImage: IMAGES.tentSunset,
    values: [
      { icon: 'shield', title: 'Safety first, always', description: 'Turn-around times are sacred. No summit is worth a risk.' },
      { icon: 'heart', title: 'Local at heart', description: 'Our crews, cooks and guides come from the valleys we trek in.' },
      { icon: 'leaf', title: 'Light footprint', description: 'Zero single-use plastic at camp and waste carried down every trip.' },
      { icon: 'compass', title: 'Honest guidance', description: "If a trek isn't right for you, we'll tell you, and suggest one that is." },
    ],
    stats: [
      { value: '2011', label: 'Founded' },
      { value: '120+', label: 'Local crew' },
      { value: '18k+', label: 'Trekkers' },
      { value: '45', label: 'Trails' },
    ],
  },

  settings: {
    siteName: 'Chal Oye',
    tagline: 'Trek · Travel · Explore',
    description: 'Guided Himalayan treks in small groups with certified trek leaders, from Kedarkantha to Everest Base Camp.',
    currency: 'INR',
    email: 'hello@chaloye.in',
    phone: '+91 98765 43210',
    whatsapp: '919876543210',
    address: '2nd Floor, Mall Road, Manali, Himachal Pradesh 175131',
    officeHours: 'Mon – Sat, 9:00 am – 7:00 pm IST',
    socials: {
      instagram: 'https://instagram.com/',
      facebook: 'https://facebook.com/',
      youtube: 'https://youtube.com/',
      twitter: 'https://x.com/',
    },
    announcement: {
      enabled: true,
      text: 'Winter 2026 batches are open: Kedarkantha & Brahmatal from ₹9,999',
      link: '/trips',
    },
  },
};
